# Generated by Django 3.0.5 on 2020-04-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('news', '0002_autor_user_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_auth',
        ),
    ]
