# Generated by Django 3.0.5 on 2020-04-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_user_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
    ]
