# Generated by Django 3.0.5 on 2020-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200424_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='name',
        ),
    ]
