# Generated by Django 3.0.5 on 2020-04-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200424_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='data',
            new_name='date',
        ),
    ]
