# Generated by Django 3.0.5 on 2020-04-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200424_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
